# _config.yml
title: "Mentat"
description: "An AI-driven inference device designed to transform medical decision-making and enhance patient care."
# Use one of GitHub Pages' supported themes. Some popular ones:
#   - minima
#   - jekyll-theme-cayman
#   - jekyll-theme-slate
#   - jekyll-theme-midnight
#   - jekyll-theme-leap-day

theme: jekyll-theme-midnight

# Set the base URL if you are using a project site
# i.e., if your site is at https://username.github.io/my-research-project
# baseurl: "/my-research-project"

# GitHub Pages automatically sets url. 
# But if you want to specify manually:
# url: "https://<username>.github.io"

# Exclude non-essential files/folders from the build
exclude:
  - README.md
  - LICENSE

# (Optional) Configure your markdown processing
markdown: kramdown
permalink: /:path/
